# Generated by Django 5.1.6 on 2025-03-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carinfo_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='year',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='image',
            field=models.ImageField(upload_to='car_image/'),
        ),
    ]
