# Generated by Django 5.1.6 on 2025-02-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(help_text='user identify, max length: 12', max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Login user name', max_length=50, null=True)),
            ],
        ),
    ]
