# Generated by Django 5.1.6 on 2025-04-21 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField(help_text='ID of the car')),
                ('car_name', models.CharField(help_text='Name of the car', max_length=100)),
                ('car_details', models.TextField(blank=True, help_text='Details of the car', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cars', to='user_info.user')),
            ],
        ),
    ]
