# Generated by Django 5.1.6 on 2025-04-21 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_year_carinfo_age_alter_carinfo_image'),
        ('user_info', '0002_favoritecar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecar',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='favoritecar',
            name='car_name',
        ),
        migrations.AddField(
            model_name='favoritecar',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.carinfo'),
        ),
    ]
