# Generated by Django 5.1.6 on 2025-05-15 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_year_carinfo_age_alter_carinfo_image'),
        ('user_info', '0004_alter_favoritecar_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='成交价格', max_digits=10)),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='下单时间')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cars.carinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user_info.user')),
            ],
        ),
    ]
